### ISSUE TITLE
PodLove Web Player

### ISSUE THREAD

**Issue by joschi** [christianuhlcc/christianuhlcc.github.io#6]
Es wäre super, wenn du einen Player wie den [Podlove Web Player](https://github.com/podlove/podlove-web-player) verwenden könntest, der einige fortgeschrittene Features wie etwa Steuerung der Abspielgeschwindigkeit unterstützt.

**Comment by christianuhlcc** [comment]
@joschi wow ich hab das Issue nicht gesehen, hab die notification verschlafen, sorry!
Schau ich mir mal an!

**Comment by joschi** [comment]
![](https://media.giphy.com/media/9NLYiOUxnKAJLIycEv/giphy.gif)
